### ISSUE TITLE
Combine the play and play_from commands

### ISSUE THREAD

**Issue by JulioLoayzaM** [JulioLoayzaM/CroissantBot#1]
Hi! This is a [`first-timers-only`](https://www.firsttimersonly.com/) issue.

This means it's aimed towards people who haven't contributed to open source before, or are just starting to. As such, it is a relatively simple issue, so people can focus more on the process of contributing rather than the complexity of the issue. 

If that's you, keep reading to find more about the problem, the expected solution, and any proposed steps towards that solution. 

## The problem

Currently there are two commands to start playing music: `play` and `play_from`. `play` takes a query (name of an artist, of a song, etc) as an argument and searches YouTube to get a result, while `play_from` takes a URL directly. For ease of use, only one command should be needed to deal with both cases.

## The solution

As it turns out, the feature is almost there: `play` can already handle both cases! Searching a video's URL in YouTube returns the same video (as it should!).

So an easy solution is to combine both commands into `play`, and use it to search both queries and URLs.

A better solution would be to detect whether the provided argument is a URL. That way, we could pass it directly to the function that actually gets the song instead of searching YouTube to get the same URL first.

## How to implement it

Basically, the steps to do this are:

- Claim this issue by commenting below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!
- Take a look at CONTRIBUTING for guidelines, and at README for some context.
- Clone the repo if you haven't already.
- Create a new branch, preferably with a descriptive such as `combine_play`.
- Go to `cogs/music.py`.
- Currently the `play` command starts at [line 206](https://github.com/JulioLoayzaM/CroissantBot/blob/main/cogs/music.py#L206) and `play_from` starts at [line 246](https://github.com/JulioLoayzaM/CroissantBot/blob/main/cogs/music.py#L246). These are the two functions to modify.
- Combine the two:
  - The new `play` function should have three parameters: the two necessary ones, `self` and `ctx`, and a `query` parameter.
  - It should use the code from the current `play` function to perform the search, and the code from `play_from` to use the new URL as it currently does: in other words, copy the code from `play` and paste it after the `await msg.edit(suppress=True)` at [line 267](https://github.com/JulioLoayzaM/CroissantBot/blob/main/cogs/music.py#L267).
- That should be it! You can create a pull request and wait for review. If you can test the changes beforehand, please do it.

In the meantime, there are a couple of bonus points you can tackle (no pressure!):
- Update the docstring, type-hints and command help to match the new function.
- Now that you should have only one `play` function, people that were using `play_from` (if any) might wonder why the bot suddenly doesn't recognize the command. To avoid this, create a new `play_from` function. This new function should be quite short:
  - It should notify the user that the command is now deprecated. You can send a message with `await ctx.send(message)`.
  - You can also add a notification by changing the help text above the function.
  - It should still take a URL as argument, but pass it immediatly to `play` with `await self.play(ctx, url)` instead of processing it first.
  - That way the `play_from` command still exists and works, but users are made aware it will go away in a future version.
- Finally, you can try to implement the better solution mentionned above: instead of blindly searching for whatever query it gets, `play` should try to recognize if the argument is a URL. If it is one, it can pass it directly to `YTDLSource.from_url` instead of searching for a result first.

That's it. :)

I said it is a simple issue, but it can be fairly overwhelming if you don't have much or any experience with `git`, `discord.py`, or even the `asyncio` library. Feel free to ask for help at any point, even (or specially) at the beginning. Remember, the idea of this issue is to help people get the hang of contributing to projects; the problem itself is just an entertaining mean to that end. As mentionned, there's also no pressure on doing the bonus points.

One last thing: I'd appreciate to have some update on your progress, at most a week after making the claim, even if it's to say you're still working on it. That way I can know whether to maintain your assignment or if I should assign it to someone else.

**Comment by TroySherlock** [comment]
Hi, I think I have done the first part but I am unable to create a pull request. Do I have to be assigned?

**Comment by SURAJITSHAW** [comment]
Hey, I want to work on these issue.

**Comment by JulioLoayzaM** [comment]
Hi @SURAJITSHAW,

Unfortunately, someone has already submitted a pull request (#2), even though they didn't claim the issue first. I'm going through their code to see if they've completed all additional tasks. If you're still interested in contributing to this repo, I'll let you know what part to work on, or if the pull request closes this issue, I'll create a new `first-timers-only` issue and notify you.

**Comment by SURAJITSHAW** [comment]
Sure thing, I will looking forward to it. And one thing I actually appreciate the way you explain the problem and also how to solve it. This was really great work thanks for that :)

**Comment by JulioLoayzaM** [comment]
Ok! I'll keep you posted then.

And I'm very glad to read that! This is my first open source project so I took some time reading how other projects presented their beginner-friendly issues. I'll try to present the next one in the same way. :)
