### ISSUE TITLE
Run Twitch.check_users inside an asyncio event loop

### ISSUE THREAD

**Issue by JulioLoayzaM** [JulioLoayzaM/CroissantBot#3]
### The problem

The `check_users` function in the Youtube cog is blocking, due to the use of `streamlink.streams`. I think this causes the bot to intermittently lose connection to Discord when the request takes too long.

### The solution

Making the function `async` and call the blocking `streamlink.streams` with `run_with_executor` should help mitigate the issue.

### How to implement it

Basically, the steps are:

- [ ] First, **claim the issue** by commenting below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!
- [ ] Take a look at CONTRIBUTING for guidelines, and at README for some context.
- [ ] Clone the repo if you haven't already.
- [ ] Create a new branch, preferably with a descriptive such as `async_check_users`.
- [ ] Go to `cogs/youtube.py`.
- [ ] Currently the `check_users` function start at [line 97](https://github.com/JulioLoayzaM/CroissantBot/blob/main/cogs/youtube.py#L97).
- [ ] Import the `asyncio` library.
- [ ] Mark the `check_users` function as `async`.
- [ ] At the beginning of the function (before the start of the `for` loop), get the event loop: normally the bot has a loop attribute so using `self.bot.loop` should work. Just in case, add an `or asyncio.get_event_loop()` like at [line 933](https://github.com/JulioLoayzaM/CroissantBot/blob/d48514fd19f7cba3291aa87d91600b184518f86a/cogs/music.py#L933) of the Music cog.
- [ ] Now, get the streams by running `streamlink.streams` using `loop.run_in_executor`. An example can be found at [line 935](https://github.com/JulioLoayzaM/CroissantBot/blob/d48514fd19f7cba3291aa87d91600b184518f86a/cogs/music.py#L935) of the Music cog.
  -  The first argument of `run_in_executor` should be `None`. The second one is the function to run and the third is the argument to pass to that function.

That's it for `cogs/youtube.py`.

- [ ] To finish the code part, don't forget to `await` the function when called in `check_youtube`, from `bot.py`.
- [ ] If everything looks good, open a pull request and wait for review!

### Conclusion

That's it. :)

I said it is a simple issue, but it can be fairly overwhelming if you don't have much or any experience with git, discord.py, or even the asyncio library. Feel free to ask for help at any point, even (or specially) at the beginning. Remember, the idea of this issue is to help people get the hang of contributing to projects; the problem itself is just an entertaining mean to that end.

One last thing: I'd appreciate to have some update on your progress, at most a week after making the claim, even if it's to say you're still working on it. That way I can know whether to maintain your assignment or if I should assign it to someone else.

**Comment by JulioLoayzaM** [comment]
Hi @SURAJITSHAW.

Here's the new issue. I haven't add the `first-timers-only` tag yet, let me know if this one interests you. :)

**Comment by SURAJITSHAW** [comment]
Yeah, definitely I like to work on that. After reading all instructions it's sounds little hard but still I wanna to give my all. So can I start working on that?

**Comment by JulioLoayzaM** [comment]
Yeah, I detailed the steps a bit more than the other one because `async` can be confusing at first. I'm assigning you then. :) Don't hesitate to ask for advice.

**Comment by SURAJITSHAW** [comment]
Hello @JulioLoayzaM , I need a little help.
The second argument of `run_in_executor` is a function, I don't get the point which function did you mention?

I attached a screenshot what changes I made by far.

![loop confusion](https://user-images.githubusercontent.com/86489581/133105854-b5b54c96-f702-4ddf-84b6-27f95fb6269b.jpg)

**Comment by JulioLoayzaM** [comment]
Hi @SURAJITSHAW,

Basically, the function `streamlink.streams` at [line 125](https://github.com/JulioLoayzaM/CroissantBot/blob/d48514fd19f7cba3291aa87d91600b184518f86a/cogs/youtube.py#L125) is causing a problem by randomly taking too much time to complete. The solution is to call that function with `loop.run_in_executor` instead of calling it normally, because now we can `await` the result. You can see an example of this at [line 935](https://github.com/JulioLoayzaM/CroissantBot/blob/d48514fd19f7cba3291aa87d91600b184518f86a/cogs/music.py#L935) of the Music cog.

Also, the bot should already have an event loop to run the function in. You can simply add `self.bot.loop or` before `asyncio.get_event_loop()`. That way it tries to get the bot's loop first, and if it returns `None`, it uses the one provided by `get_event_loop`.

Let me know if this clears things up! If you've never used the `asyncio` library before it can get pretty confusing.

**Comment by JulioLoayzaM** [comment]
Hi @SURAJITSHAW, did you make some progress on this?

**Comment by SURAJITSHAW** [comment]
No, I don't think I can do it. I'm sorry for wasting your time. You should reassign it to someone else.

**Comment by JulioLoayzaM** [comment]
@SURAJITSHAW don't worry, that's what the issue was for. If you want, I can tell you *exactly* what to change so you can submit a pull request.

**Comment by SURAJITSHAW** [comment]
Oh thank you so much. I have never expected that much support 🥺. Please tell me what should I change exactly.

**Comment by JulioLoayzaM** [comment]
Alright!

In `cogs/youtube.by`:
- [ ] Just before `import json` add `import asyncio`.
- [ ] Change `def check_users` to `async def check_users`
- [ ] According to your screenshot, you have the loop line. If not, add `loop = asyncio.get_event_loop()` before `for streamer in streamers.keys()`
- [ ] Just below the `try`, change `streams = streamlink.streams(channel)` to `streams = await loop.run_in_executor(None, streamlink.streams, channel)`

In `bot.py`:
- [ ] At line 549, change `messages, YT_PREV_STATUS = youtube.check_users(YT_PREV_STATUS, YT_STREAMERS)` to `messages, YT_PREV_STATUS = await youtube.check_users(YT_PREV_STATUS, YT_STREAMERS)` (add an `await`)

And that's it. :) I think the `run_in_executor` part was too confusing for a first-timers issue.

After finishing the steps you can open a pull request. Could you please try to open one against the 'develop' branch? If it doesn't work, just open one against 'main'.

**Comment by JulioLoayzaM** [comment]
That's it @SURAJITSHAW , thank you for your contribution!

**Comment by SURAJITSHAW** [comment]
Thanks to you I can make my first successful contribution.🤗
